const MAP_WIDTH=20000,MAP_HEIGHT=20000,TILE_SIZE=256,MIN_ZOOM=12,MAX_ZOOM=18;
const viewport=document.getElementById('mapViewport'),mapWorld=document.getElementById('mapWorld'),tileLayer=document.getElementById('tileLayer'),routeLayer=document.getElementById('routeLayer'),markerLayer=document.getElementById('markerLayer'),playerLayer=document.getElementById('playerLayer');
let telemetry=null,markers=[],selectedPoi=null,routeTarget=null,currentRoute=null,navMode=false,northUp=(localStorage.getItem('fh6_north_up')==='1'),follow=true,showMarkers=true,zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,Math.round(Number(localStorage.getItem('fh6_zoom')||16)))),layerId=localStorage.getItem('fh6_layer')||"760",categoryFilter=localStorage.getItem('fh6_category')||"",panX=0,panY=0,dragging=false,dragStart=null,playerMapX=10387,playerMapY=9846,targetMapX=null,targetMapY=null,displayMapX=null,displayMapY=null,targetHeadingDeg=0,displayHeadingDeg=0,lastTelemetryMapX=null,lastTelemetryMapY=null,lastMovementHeadingDeg=null,lastMovementHeadingAt=0,lastTileKey="",activePointers=new Map(),pinchStart=null,lastPinchZoom=zoom,lastMarkerRenderAt=0,lastNearestRenderAt=0,lastRouteRequestAt=0,routeRequestInFlight=false,lastRouteAnchorX=null,lastRouteAnchorY=null,lastRouteOffRoutePx=0,offRouteSince=0,navTouchLookUntil=0;
let markerDomByKey=new Map(),playerEl=null,routeEls=null,lastRouteSize='',lastRoutePoints='',interactionRenderRaf=0,arriveSince=0,mapContextTarget=null,mapContextMenuEl=null,mapPickEl=null,lastTapAt=0,lastTapX=0,lastTapY=0,lastManualZoomAt=0,lastAutoZoomCheckAt=0,autoZoomInCandidate=null,autoZoomInCandidateAt=0,tapStart=null,tapWasMulti=false;
const NAV_TOUCH_LOOK_MS=0,REROUTE_MIN_INTERVAL_MS=14000,REROUTE_STICKY_OFF_PX=170,REROUTE_STICKY_MS=22000,REROUTE_HARD_OFF_PX=360,REROUTE_HARD_MS=9000,REROUTE_HUGE_OFF_PX=650,REROUTE_HUGE_MS=3500,REROUTE_REFRESH_MOVE_PX=760,REROUTE_LONG_ROUTE_LOCK_MS=32000;
const MAP_PX_PER_METER=0.655,NAV_ARRIVE_METERS=30,NAV_ARRIVE_STOPPED_METERS=62,NAV_ARRIVE_PX=NAV_ARRIVE_METERS*MAP_PX_PER_METER,NAV_ARRIVE_STOPPED_PX=NAV_ARRIVE_STOPPED_METERS*MAP_PX_PER_METER,NAV_ARRIVE_STOPPED_MAX_KMH=8,NAV_ARRIVE_HOLD_MS=1100;
const FALLBACK_IMG_W=1638,FALLBACK_IMG_H=2048,FALLBACK_SX=6.58487266,FALLBACK_SY=6.60554791,FALLBACK_OX=4594.21749925,FALLBACK_OY=3225.79270983;
const NAV_AUTO_ZOOM_SECONDS=4.0,NAV_AUTO_ZOOM_MIN_METERS=170,NAV_AUTO_ZOOM_HOLD_IN_MS=4200,NAV_AUTO_ZOOM_CHECK_MS=450,NAV_AUTO_ZOOM_MANUAL_COOLDOWN_MS=5500,NAV_AUTO_ZOOM_MIN_ZOOM=15,NAV_AUTO_ZOOM_TOP_MARGIN=128,NAV_AUTO_ZOOM_SIDE_MARGIN=42,NAV_AUTO_ZOOM_BOTTOM_MARGIN=96;

// v0.9.15 compact lower-left nearest POI
let mobileActivePanel=null;
function isMobileLayout(){return window.matchMedia('(max-width:760px), (pointer:coarse)').matches}
function setMobileUiClass(){document.body.classList.toggle('mobileUi',isMobileLayout())}
function setDockActive(panel){document.querySelectorAll('.mobileDockBtn').forEach(btn=>btn.classList.toggle('active',btn.dataset.panel===panel));}
function closeMobilePanels(){
  mobileActivePanel=null;
  document.querySelectorAll('.mobileSheet').forEach(el=>el.classList.remove('mobileOpen'));
  document.getElementById('app').classList.remove('mediaOpen');
  document.getElementById('app').classList.remove('nearestOpen');
  setDockActive(null);
}
function openMobilePanel(panel){
  setMobileUiClass();
  const app=document.getElementById('app');
  const same=mobileActivePanel===panel || (panel==='media'&&app.classList.contains('mediaOpen'));
  closeMobilePanels();
  if(same)return;
  mobileActivePanel=panel;
  setDockActive(panel);
  if(panel==='media'){
    app.classList.remove('mediaCollapsed');
    app.classList.add('mediaOpen');
    return;
  }
  const el=document.querySelector('.mobileSheet[data-mobile-panel="'+panel+'"]');
  if(el)el.classList.add('mobileOpen');
  if(panel==='info'){app.classList.add('nearestOpen');updateNearest();}
  if(panel==='search')setTimeout(()=>document.getElementById('searchInput')?.focus(),70);
}

function isNavTouchLookActive(){return false}
function keepNavigatorFollow(){if(navMode)follow=true;const btn=document.getElementById('followBtn');if(btn)btn.classList.add('active')}
function suspendNavFollow(ms=NAV_TOUCH_LOOK_MS){if(navMode&&follow){navTouchLookUntil=0;keepNavigatorFollow()}}
function centerIfFollowing(){if(follow)centerOnPlayer()}
function setFollowEnabled(value){follow=!!value;const btn=document.getElementById('followBtn');if(btn)btn.classList.toggle('active',follow);if(follow){navTouchLookUntil=0;centerOnPlayer();renderTiles(true);renderPlayer();renderMarkers();renderRouteLine();updateNearest();}}
function toggleNearestOverlay(){
  const app=document.getElementById('app');
  const next=!app.classList.contains('nearestOpen');
  closeMobilePanels();
  app.classList.toggle('nearestOpen',next);
  if(next)updateNearest();
}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function scale(){return Math.pow(2,zoom-MAX_ZOOM)}function mapToScreen(mx,my){const s=scale();return{x:mx*s-panX,y:my*s-panY}}function rotatePointAround(px,py,cx,cy,deg){if(!deg)return{x:px,y:py};const rad=deg*Math.PI/180,cos=Math.cos(rad),sin=Math.sin(rad),dx=px-cx,dy=py-cy;return{x:cx+dx*cos-dy*sin,y:cy+dx*sin+dy*cos}}function screenToMap(sx,sy){const a=navAnchor(),deg=navRotationDeg();const u=rotatePointAround(sx,sy,a.x,a.y,-deg);const s=scale();return{x:(u.x+panX)/s,y:(u.y+panY)/s}}function dist(a,b){const dx=a.map_x-b.map_x,dy=a.map_y-b.map_y;return Math.sqrt(dx*dx+dy*dy)}function metersFromMapPx(px){return px/MAP_PX_PER_METER}function mapPxFromMeters(m){return m*MAP_PX_PER_METER}
function initControls(){
  document.getElementById('layerSelect').value=layerId;
  document.getElementById('categorySelect').value=categoryFilter;
  const northBtn=document.getElementById('northUpBtn');
  if(northBtn)northBtn.classList.toggle('active',northUp);
  document.getElementById('followBtn').classList.add('active');
  follow=true;
  document.getElementById('followBtn').onclick=()=>setFollowEnabled(!follow);
  document.getElementById('navBtn').onclick=()=>enterNavMode();
  if(northBtn)northBtn.onclick=()=>{setNorthUp(!northUp);lastTileKey='';renderAll(true)};
  document.getElementById('navExitBtn').onclick=()=>exitNavMode();
  document.getElementById('mediaPrevBtn').onclick=()=>sendMediaKey('prev');
  document.getElementById('mediaPlayBtn').onclick=()=>sendMediaKey('playpause');
  document.getElementById('mediaNextBtn').onclick=()=>sendMediaKey('next');
  document.getElementById('mediaVolDownBtn').onclick=()=>sendMediaKey('voldown');
  document.getElementById('mediaVolUpBtn').onclick=()=>sendMediaKey('volup');
  document.getElementById('mediaCollapseBtn')?.addEventListener('click',()=>{const app=document.getElementById('app');app.classList.remove('mediaOpen');app.classList.add('mediaCollapsed');mobileActivePanel=null;setDockActive(null);});
  document.getElementById('navMediaToggleBtn')?.addEventListener('click',()=>openMobilePanel('media'));
  document.getElementById('navInfoToggleBtn')?.addEventListener('click',()=>toggleNearestOverlay());
  document.getElementById('mobileNearestCloseBtn')?.addEventListener('click',()=>document.getElementById('app').classList.remove('nearestOpen'));
  document.querySelectorAll('.mobileDockBtn').forEach(btn=>btn.addEventListener('click',()=>openMobilePanel(btn.dataset.panel)));
  document.querySelectorAll('[data-close-mobile]').forEach(btn=>btn.addEventListener('click',()=>closeMobilePanels()));
  document.getElementById('markersBtn').onclick=()=>{showMarkers=!showMarkers;document.getElementById('markersBtn').classList.toggle('active',showMarkers);renderMarkers()};
  document.getElementById('layerSelect').onchange=e=>{layerId=e.target.value;localStorage.setItem('fh6_layer',layerId);tileLayer.innerHTML="";lastTileKey="";renderTiles(true)};
  document.getElementById('categorySelect').onchange=e=>{categoryFilter=e.target.value;localStorage.setItem('fh6_category',categoryFilter);renderMarkers();updateNearest();runSearch(document.getElementById('searchInput')?.value||'')};
  initSearch();
}
function setNorthUp(value){northUp=!!value;localStorage.setItem('fh6_north_up',northUp?'1':'0');const northBtn=document.getElementById('northUpBtn');if(northBtn)northBtn.classList.toggle('active',northUp);applyMapRotation()}
function setZoom(n,cx=null,cy=null,opts={}){const isAuto=!!(opts&&opts.auto);n=clamp(Math.round(n),MIN_ZOOM,MAX_ZOOM);if(!isAuto)lastManualZoomAt=Date.now();if(n===zoom)return;let anchor;if(cx!==null&&cy!==null){const r0=viewport.getBoundingClientRect();anchor=screenToMap(cx-r0.left,cy-r0.top)}else anchor={x:playerMapX,y:playerMapY};zoom=n;if(!isAuto)localStorage.setItem('fh6_zoom',String(zoom));const r=viewport.getBoundingClientRect(),s=scale();if(cx!==null&&cy!==null){panX=anchor.x*s-(cx-r.left);panY=anchor.y*s-(cy-r.top)}else centerOnPlayer();clampPan();tileLayer.innerHTML="";lastTileKey="";applyMapRotation();renderAll(true)}
function centerOnPlayer(){const a=navAnchor(),s=scale();panX=playerMapX*s-a.x;panY=playerMapY*s-a.y;clampPan();applyMapRotation()}
function clampPan(){const r=viewport.getBoundingClientRect(),s=scale(),ww=MAP_WIDTH*s,hh=MAP_HEIGHT*s;if(ww<=r.width)panX=(ww-r.width)/2;else panX=clamp(panX,0,ww-r.width);if(hh<=r.height)panY=(hh-r.height)/2;else panY=clamp(panY,0,hh-r.height)}
function navAnchor(){const r=viewport.getBoundingClientRect();return{x:r.width/2,y:navMode?r.height*0.68:r.height/2}}
function navRotationDeg(){return (navMode&&follow&&routeTarget&&!northUp)?-(displayHeadingDeg||0):0}
function normalizeAngleDeg(deg){return ((Number(deg)||0)%360+360)%360}
function mapVectorToHeadingDeg(dx,dy){return normalizeAngleDeg(Math.atan2(dx,-dy)*180/Math.PI)}
function updateHeadingFromMotion(mx,my,speedKmh,serverHeadingDeg){let heading=Number(serverHeadingDeg)||0;const now=performance.now();if(lastTelemetryMapX!==null&&lastTelemetryMapY!==null){const dx=mx-lastTelemetryMapX,dy=my-lastTelemetryMapY,step=Math.hypot(dx,dy);if(step>0.45&&(speedKmh||0)>2){heading=mapVectorToHeadingDeg(dx,dy);lastMovementHeadingDeg=heading;lastMovementHeadingAt=now}else if(lastMovementHeadingDeg!==null&&(now-lastMovementHeadingAt)<3500){heading=lastMovementHeadingDeg}}lastTelemetryMapX=mx;lastTelemetryMapY=my;return normalizeAngleDeg(heading)}
function applyMapRotation(){const a=navAnchor(),deg=navRotationDeg();if(mapWorld){mapWorld.style.transformOrigin=`${a.x}px ${a.y}px`;mapWorld.style.transform=`rotate(${deg}deg)`}}

function renderMapFallback(){const img=document.getElementById('mapFallback');if(!img)return;const s=scale();img.style.left=`${(FALLBACK_OX*s-panX).toFixed(1)}px`;img.style.top=`${(FALLBACK_OY*s-panY).toFixed(1)}px`;img.style.width=`${(FALLBACK_IMG_W*FALLBACK_SX*s).toFixed(1)}px`;img.style.height=`${(FALLBACK_IMG_H*FALLBACK_SY*s).toFixed(1)}px`}
function renderTiles(force=false){renderMapFallback();const r=viewport.getBoundingClientRect(),s=scale(),margin=navMode?5:1,x0=Math.floor(panX/TILE_SIZE)-margin,y0=Math.floor(panY/TILE_SIZE)-margin,x1=Math.ceil((panX+r.width)/TILE_SIZE)+margin,y1=Math.ceil((panY+r.height)/TILE_SIZE)+margin,maxTx=Math.ceil((MAP_WIDTH*s)/TILE_SIZE)-1,maxTy=Math.ceil((MAP_HEIGHT*s)/TILE_SIZE)-1,key=[zoom,layerId,x0,y0,x1,y1,Math.round(panX),Math.round(panY)].join(':');if(!force&&key===lastTileKey){applyMapRotation();return}lastTileKey=key;const need=new Set();for(let ty=y0;ty<=y1;ty++)for(let tx=x0;tx<=x1;tx++){if(tx<0||ty<0||tx>maxTx||ty>maxTy)continue;const id=`${zoom}-${tx}-${ty}`;need.add(id);let img=document.getElementById('tile-'+id);if(!img){img=document.createElement('img');img.className='tile';img.id='tile-'+id;img.decoding='async';img.loading='eager';img.src=`/tile/${layerId}/${zoom}/${tx}/${ty}.png`;img.onerror=()=>{img.style.opacity=0};tileLayer.appendChild(img)}img.style.left=`${tx*TILE_SIZE-panX}px`;img.style.top=`${ty*TILE_SIZE-panY}px`}for(const img of Array.from(tileLayer.children))if(!need.has(img.id.replace('tile-','')))img.remove();applyMapRotation()}
function renderPlayer(){if(playerMapX===null||playerMapY===null){if(playerEl)playerEl.style.display='none';return}if(!playerEl){playerEl=document.createElement('div');playerEl.className='player';playerLayer.appendChild(playerEl)}const p=mapToScreen(playerMapX,playerMapY);playerEl.style.display='block';playerEl.style.left=`${p.x}px`;playerEl.style.top=`${p.y}px`}
function populateCategories(){const cats=[...new Set(markers.map(m=>m.category).filter(Boolean))].sort(),sel=document.getElementById('categorySelect');for(const c of cats){let o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o)}if(categoryFilter)sel.value=categoryFilter}
function markerKey(m){return String(m.markerId||m.id||((m.title||'poi')+'@'+Math.round(m.map_x)+','+Math.round(m.map_y)))}
function renderMarkers(){if(!showMarkers){for(const el of markerDomByKey.values())el.remove();markerDomByKey.clear();const popup=document.getElementById('poiPopup');if(popup)popup.remove();return}if(!markers||!markers.length){const popup=document.getElementById('poiPopup');if(popup)popup.remove();return}const r=viewport.getBoundingClientRect(),pad=navMode?Math.max(r.width,r.height):80;let pool=markers;if(categoryFilter)pool=pool.filter(m=>m.category===categoryFilter);const need=new Set();let count=0;for(const m of pool){const p=mapToScreen(m.map_x,m.map_y);if(p.x<-pad||p.y<-pad||p.x>r.width+pad||p.y>r.height+pad)continue;const key=markerKey(m);need.add(key);let d=markerDomByKey.get(key);if(!d){d=document.createElement('div');d.onpointerdown=(ev)=>{ev.stopPropagation();selectPoi(d._fh6Marker,true)};markerDomByKey.set(key,d);markerLayer.appendChild(d)}d._fh6Marker=m;const isSpeed=/speed/i.test(m.category||"");const selected=selectedPoi&&String(selectedPoi.markerId||selectedPoi.id)===String(m.markerId||m.id);d.className='marker'+(isSpeed?' speed':'')+(selected?' selected':'');d.style.left=`${p.x}px`;d.style.top=`${p.y}px`;d.style.background=m.color||'#7dd3fc';d.title=`${m.title} | ${m.category}`;if(++count>600)break}for(const [key,el] of Array.from(markerDomByKey.entries())){if(!need.has(key)){el.remove();markerDomByKey.delete(key)}}renderPoiPopup();applyMapRotation()}
function selectPoi(m,keepMap=false){selectedPoi=m;if(!keepMap&&!navMode){follow=false;document.getElementById('followBtn').classList.remove('active');const r=viewport.getBoundingClientRect(),s=scale();panX=m.map_x*s-r.width/2;panY=m.map_y*s-r.height/2;clampPan()}else if(navMode){keepNavigatorFollow()}renderMarkers();updateNearest()}
function clearPoi(){selectedPoi=null;closeMapContextMenu(true);renderMarkers();updateNearest()}
function renderPoiPopup(){const old=document.getElementById('poiPopup');if(old)old.remove();if(!selectedPoi)return;const p=mapToScreen(selectedPoi.map_x,selectedPoi.map_y);const r=viewport.getBoundingClientRect();const popup=document.createElement('div');popup.id='poiPopup';popup.className='poiPopup';let distanceText='—';if(telemetry&&telemetry.map_x!==null){distanceText=markerDistanceText(selectedPoi)||'—'}const desc=selectedPoi.description||selectedPoi.desc||'Description slot is ready. Later we can load richer GamerGuides popup text here.';popup.innerHTML=`<button class="poiPopupClose" title="Close">×</button><div class="poiPopupTitle">${esc(selectedPoi.title||'Unknown POI')}</div><div class="poiPopupMeta">${esc(selectedPoi.category||'Unknown category')}${selectedPoi.parent_category?' · '+esc(selectedPoi.parent_category):''}</div><div class="poiPopupDesc">${esc(desc)}</div><div class="poiPopupRow"><span>Map coordinates</span><b>${Math.round(selectedPoi.map_x)}, ${Math.round(selectedPoi.map_y)}</b></div><div class="poiPopupRow"><span>Distance from car</span><b>${distanceText}</b></div><div class="poiPopupActions"><button class="routeBtn" id="buildRouteBtn">Build route</button></div>`;popup.querySelector('.poiPopupClose').onclick=(ev)=>{ev.stopPropagation();clearPoi()};const buildBtn=popup.querySelector('#buildRouteBtn');buildBtn.onpointerdown=(ev)=>{ev.preventDefault();ev.stopPropagation();startRouteToPoi(selectedPoi)};markerLayer.appendChild(popup);let left=p.x+18,top=p.y-24;if(left+330>r.width)left=p.x-348;if(top+210>r.height)top=r.height-226;if(top<10)top=10;if(left<10)left=10;popup.style.left=`${left}px`;popup.style.top=`${top}px`}
function makeMapPointTarget(mx,my){return{isCustom:true,title:'Selected point',category:'Custom point',map_x:mx,map_y:my}}
function closeMapContextMenu(clearTarget=true){if(mapContextMenuEl){mapContextMenuEl.remove();mapContextMenuEl=null}if(clearTarget){mapContextTarget=null;if(mapPickEl){mapPickEl.remove();mapPickEl=null}}}
function renderMapPickMarker(){if(!mapContextTarget){if(mapPickEl)mapPickEl.style.display='none';return}if(!mapPickEl){mapPickEl=document.createElement('div');mapPickEl.className='mapPickMarker';markerLayer.appendChild(mapPickEl)}const p=mapToScreen(mapContextTarget.map_x,mapContextTarget.map_y);mapPickEl.style.display='block';mapPickEl.style.left=`${p.x}px`;mapPickEl.style.top=`${p.y}px`}
function showMapContextMenu(mx,my,clientX,clientY,source='map'){closeMapContextMenu(true);clearPoi();mapContextTarget=makeMapPointTarget(mx,my);renderMapPickMarker();const r=viewport.getBoundingClientRect();const menu=document.createElement('div');menu.className='mapContextMenu';const meters=telemetry&&telemetry.map_x!==null?Math.round(metersFromMapPx(dist({map_x:telemetry.map_x,map_y:telemetry.map_y},mapContextTarget))):null;menu.innerHTML=`<div class="mapContextTitle">Selected point</div><div class="mapContextMeta">${Math.round(mx)}, ${Math.round(my)}${meters!==null?' · '+(meters>=1000?(meters/1000).toFixed(1)+' km':meters+' m'):''}</div><button class="mapContextRoute">Build route</button><button class="mapContextCancel">Cancel</button>`;menu.querySelector('.mapContextRoute').onpointerdown=(ev)=>{ev.preventDefault();ev.stopPropagation();const target=mapContextTarget;closeMapContextMenu(true);startRouteToPoi(target)};menu.querySelector('.mapContextCancel').onpointerdown=(ev)=>{ev.preventDefault();ev.stopPropagation();closeMapContextMenu(true)};viewport.appendChild(menu);mapContextMenuEl=menu;let left=clientX-r.left,top=clientY-r.top;if(left+220>r.width)left=r.width-230;if(top+132>r.height)top=r.height-142;if(left<10)left=10;if(top<10)top=10;menu.style.left=left+'px';menu.style.top=top+'px'}
function showContextMenuForScreen(clientX,clientY,useCrosshair=false){const r=viewport.getBoundingClientRect();const sx=useCrosshair?r.width/2:clientX-r.left,sy=useCrosshair?r.height/2:clientY-r.top;const m=screenToMap(sx,sy);const menuX=useCrosshair?r.left+r.width/2:clientX,menuY=useCrosshair?r.top+r.height/2:clientY;showMapContextMenu(clamp(m.x,0,MAP_WIDTH),clamp(m.y,0,MAP_HEIGHT),menuX,menuY,useCrosshair?'crosshair':'map')}
function maybeHandleDoubleTap(e){if(!isMobileLayout()&&(navigator.maxTouchPoints||0)<2)return false;const now=Date.now(),dx=e.clientX-lastTapX,dy=e.clientY-lastTapY;const hit=(now-lastTapAt)<460&&Math.hypot(dx,dy)<44;if(hit){lastTapAt=0;showContextMenuForScreen(e.clientX,e.clientY,true);return true}lastTapAt=now;lastTapX=e.clientX;lastTapY=e.clientY;return false}

async function startRouteToPoi(poi){if(!poi)return;closeMapContextMenu(true);routeTarget=poi;selectedPoi=null;currentRoute=null;lastRouteAnchorX=null;lastRouteAnchorY=null;lastRouteOffRoutePx=0;offRouteSince=0;autoZoomInCandidate=null;autoZoomInCandidateAt=0;await requestRoute(poi,true);enterNavMode(true)}
async function requestRoute(target,force=false){if(!target)return null;if(routeRequestInFlight&&!force)return currentRoute;const now=Date.now();if(!force&&now-lastRouteRequestAt<2200)return currentRoute;routeRequestInFlight=true;lastRouteRequestAt=now;try{const qs=new URLSearchParams({target_x:String(target.map_x),target_y:String(target.map_y),target_title:String(target.title||'Destination')});if(!target.isCustom&&(target.markerId||target.id))qs.set('marker_id',String(target.markerId||target.id));const r=await fetch('/api/route?'+qs.toString(),{cache:'no-store'});const data=await r.json();if(data){const incomingPts=Array.isArray(data.polyline)?data.polyline.map(p=>({map_x:Number(p.map_x),map_y:Number(p.map_y)})).filter(p=>Number.isFinite(p.map_x)&&Number.isFinite(p.map_y)):[];const incomingDist=incomingPts.length>=2?routeDistancePx(incomingPts):Infinity;const currentRemaining=routePointsForRender();const currentRemainingDist=currentRemaining.length>=2?routeDistancePx(currentRemaining):Infinity;const off=telemetry&&telemetry.map_x!==null?distanceToCurrentRoute(Number(telemetry.map_x),Number(telemetry.map_y)):Infinity;const holdingOriginalRoute=!!offRouteSince&&((now-offRouteSince)<REROUTE_LONG_ROUTE_LOCK_MS);const suspiciousReroute=!force&&currentRoute&&currentRoute.mode==='graph'&&data.mode==='graph'&&Number.isFinite(incomingDist)&&Number.isFinite(currentRemainingDist)&&incomingDist>Math.max(currentRemainingDist*1.25,currentRemainingDist+350)&&off<520&&holdingOriginalRoute;if(suspiciousReroute){console.warn('FH6 route ignored sticky reroute', {incomingDist,currentRemainingDist,off,heldForMs:now-offRouteSince,data});return currentRoute}currentRoute=data;currentRoute.client_requested_at=Date.now();offRouteSince=0;console.log('FH6 route',data.mode,data.message||'',data.routing||{});if(telemetry&&telemetry.map_x!==null){lastRouteAnchorX=Number(telemetry.map_x);lastRouteAnchorY=Number(telemetry.map_y)}}else{currentRoute=null}return currentRoute}catch(e){console.warn('route request failed',e);return currentRoute}finally{routeRequestInFlight=false}}
function pointSegmentDistance(px,py,ax,ay,bx,by){const vx=bx-ax,vy=by-ay,wx=px-ax,wy=py-ay;const c1=vx*wx+vy*wy;const c2=vx*vx+vy*vy;if(c2<=0)return{d:Math.hypot(px-ax,py-ay),x:ax,y:ay,t:0};let t=c1/c2;t=clamp(t,0,1);const x=ax+vx*t,y=ay+vy*t;return{d:Math.hypot(px-x,py-y),x,y,t}}
function normalizedRoutePolyline(){if(!currentRoute||!Array.isArray(currentRoute.polyline))return[];return currentRoute.polyline.map(p=>({map_x:Number(p.map_x),map_y:Number(p.map_y)})).filter(p=>Number.isFinite(p.map_x)&&Number.isFinite(p.map_y))}
function routeDistancePx(pts){let total=0;if(!pts||pts.length<2)return 0;for(let i=1;i<pts.length;i++)total+=Math.hypot(pts[i].map_x-pts[i-1].map_x,pts[i].map_y-pts[i-1].map_y);return total}
function trimRoutePolyline(raw,px,py){if(!raw||raw.length<2)return[];let best={d:Infinity,i:0,x:raw[0].map_x,y:raw[0].map_y,t:0};for(let i=0;i<raw.length-1;i++){const a=raw[i],b=raw[i+1];const hit=pointSegmentDistance(px,py,a.map_x,a.map_y,b.map_x,b.map_y);if(hit.d<best.d)best={...hit,i}}lastRouteOffRoutePx=best.d;const remaining=[];if(best.d<160){remaining.push({map_x:best.x,map_y:best.y});const startIdx=best.t>0.72?best.i+2:best.i+1;for(let j=startIdx;j<raw.length;j++)remaining.push(raw[j])}else{for(let j=1;j<raw.length;j++)remaining.push(raw[j])}if(remaining.length&&Math.hypot(remaining[0].map_x-px,remaining[0].map_y-py)<3)remaining.shift();return remaining}
function distanceToCurrentRoute(px,py){const raw=normalizedRoutePolyline();if(raw.length<2)return Infinity;let best=Infinity;for(let i=0;i<raw.length-1;i++){const a=raw[i],b=raw[i+1];const hit=pointSegmentDistance(px,py,a.map_x,a.map_y,b.map_x,b.map_y);if(hit.d<best)best=hit.d}return best}
function routePointAtDistance(pts,wantPx){if(!pts||pts.length<2)return pts&&pts.length?pts[pts.length-1]:null;let left=wantPx;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],seg=Math.hypot(b.map_x-a.map_x,b.map_y-a.map_y);if(seg<=0)continue;if(left<=seg){const t=left/seg;return{map_x:a.map_x+(b.map_x-a.map_x)*t,map_y:a.map_y+(b.map_y-a.map_y)*t}}left-=seg}return pts[pts.length-1]}
function desiredNavZoomForSpeed(){if(!navMode||!follow||!routeTarget||!telemetry||telemetry.map_x===null)return zoom;const pts=routePointsForRender();if(!pts||pts.length<2)return zoom;const speed=Number(telemetry.speed_kmh)||0;const lookMeters=Math.max(NAV_AUTO_ZOOM_MIN_METERS,(speed/3.6)*NAV_AUTO_ZOOM_SECONDS);const lookPx=mapPxFromMeters(lookMeters);const look=routePointAtDistance(pts,lookPx);if(!look)return zoom;const r=viewport.getBoundingClientRect(),a=navAnchor(),deg=navRotationDeg();function panFor(z){const s=Math.pow(2,z-MAX_ZOOM);let px=playerMapX*s-a.x,py=playerMapY*s-a.y;const ww=MAP_WIDTH*s,hh=MAP_HEIGHT*s;if(ww<=r.width)px=(ww-r.width)/2;else px=clamp(px,0,ww-r.width);if(hh<=r.height)py=(hh-r.height)/2;else py=clamp(py,0,hh-r.height);return{px,py,s}}for(let z=MAX_ZOOM;z>=NAV_AUTO_ZOOM_MIN_ZOOM;z--){const pp=panFor(z);const raw={x:look.map_x*pp.s-pp.px,y:look.map_y*pp.s-pp.py};const screen=rotatePointAround(raw.x,raw.y,a.x,a.y,deg);if(screen.x>=NAV_AUTO_ZOOM_SIDE_MARGIN&&screen.x<=r.width-NAV_AUTO_ZOOM_SIDE_MARGIN&&screen.y>=NAV_AUTO_ZOOM_TOP_MARGIN&&screen.y<=r.height-NAV_AUTO_ZOOM_BOTTOM_MARGIN)return z}return NAV_AUTO_ZOOM_MIN_ZOOM}
function maybeAutoZoomNavigation(){if(!navMode||!follow||!routeTarget||!telemetry||telemetry.map_x===null)return;const now=Date.now();if(now-lastManualZoomAt<NAV_AUTO_ZOOM_MANUAL_COOLDOWN_MS)return;if(now-lastAutoZoomCheckAt<NAV_AUTO_ZOOM_CHECK_MS)return;lastAutoZoomCheckAt=now;const desired=desiredNavZoomForSpeed();if(desired<zoom){autoZoomInCandidate=null;autoZoomInCandidateAt=0;setZoom(desired,null,null,{auto:true});return}if(desired>zoom){if(autoZoomInCandidate!==desired){autoZoomInCandidate=desired;autoZoomInCandidateAt=now;return}if(now-autoZoomInCandidateAt>=NAV_AUTO_ZOOM_HOLD_IN_MS){autoZoomInCandidate=null;autoZoomInCandidateAt=0;setZoom(desired,null,null,{auto:true})}}else{autoZoomInCandidate=null;autoZoomInCandidateAt=0}}
function maybeRerouteNavigation(){if(!navMode||!routeTarget||!telemetry||telemetry.map_x===null||routeRequestInFlight)return;const now=Date.now();const px=Number(telemetry.map_x),py=Number(telemetry.map_y);const toTarget=dist({map_x:px,map_y:py},routeTarget);if(toTarget<35)return;const weakRoute=(!currentRoute||!Array.isArray(currentRoute.polyline)||currentRoute.polyline.length<2);if(weakRoute){if(now-lastRouteRequestAt>2800)requestRoute(routeTarget,false);return}const off=distanceToCurrentRoute(px,py);lastRouteOffRoutePx=off;const moved=(lastRouteAnchorX===null||lastRouteAnchorY===null)?0:Math.hypot(px-lastRouteAnchorX,py-lastRouteAnchorY);if(off<=REROUTE_STICKY_OFF_PX){offRouteSince=0;if(moved>REROUTE_REFRESH_MOVE_PX&&now-lastRouteRequestAt>16000)requestRoute(routeTarget,false);return}if(!offRouteSince)offRouteSince=now;const offMs=now-offRouteSince;if(now-lastRouteRequestAt<REROUTE_MIN_INTERVAL_MS)return;const shouldReroute=(off>REROUTE_HUGE_OFF_PX&&offMs>REROUTE_HUGE_MS)||(off>REROUTE_HARD_OFF_PX&&offMs>REROUTE_HARD_MS)||(off>REROUTE_STICKY_OFF_PX&&offMs>REROUTE_STICKY_MS);if(shouldReroute)requestRoute(routeTarget,false)}
function enterNavMode(forceHeadingUp=false){closeMobilePanels();navMode=true;follow=true;document.getElementById('app').classList.add('navMode');document.getElementById('followBtn').classList.add('active');if(!routeTarget&&selectedPoi)routeTarget=selectedPoi;if(forceHeadingUp&&routeTarget)setNorthUp(false);setZoom(Math.max(zoom,17),null,null,{auto:true});centerOnPlayer();renderTiles(true);renderPlayer();renderMarkers();renderRouteLine();updateNearest();updateNavUi()}
function exitNavMode(){closeMobilePanels();navMode=false;document.getElementById('app').classList.remove('navMode');applyMapRotation();renderAll(true)}
function routePointsForRender(){if(!routeTarget||playerMapX===null||playerMapY===null)return[];const pts=[{map_x:playerMapX,map_y:playerMapY}];const raw=normalizedRoutePolyline();if(raw.length>=2){const tail=trimRoutePolyline(raw,playerMapX,playerMapY);for(const p of tail)pts.push(p)}else if(currentRoute&&currentRoute.mode==='direct'){pts.push({map_x:routeTarget.map_x,map_y:routeTarget.map_y})}else{return[]}return pts.filter(p=>Number.isFinite(p.map_x)&&Number.isFinite(p.map_y))}
function ensureRouteEls(){if(routeEls)return routeEls;routeLayer.innerHTML='';const ns='http://www.w3.org/2000/svg';const outer=document.createElementNS(ns,'polyline');outer.setAttribute('fill','none');outer.setAttribute('stroke','#63f000');outer.setAttribute('stroke-width','10');outer.setAttribute('stroke-linecap','round');outer.setAttribute('stroke-linejoin','round');outer.setAttribute('opacity','0.96');const inner=document.createElementNS(ns,'polyline');inner.setAttribute('fill','none');inner.setAttribute('stroke','rgba(255,255,255,.82)');inner.setAttribute('stroke-width','3');inner.setAttribute('stroke-linecap','round');inner.setAttribute('stroke-linejoin','round');inner.setAttribute('opacity','0.85');const dest=document.createElementNS(ns,'circle');dest.setAttribute('r','13');dest.setAttribute('fill','#ef4444');dest.setAttribute('stroke','#fff');dest.setAttribute('stroke-width','4');routeLayer.appendChild(outer);routeLayer.appendChild(inner);routeLayer.appendChild(dest);routeEls={outer,inner,dest};return routeEls}
function renderRouteLine(){if(!routeTarget||playerMapX===null||playerMapY===null){routeLayer.style.display='none';routeLayer.innerHTML='';routeEls=null;lastRoutePoints='';return}const pts=routePointsForRender();if(pts.length<2){routeLayer.style.display='none';routeLayer.innerHTML='';routeEls=null;lastRoutePoints='';return}const r=viewport.getBoundingClientRect();const w=Math.round(r.width),h=Math.round(r.height),sizeSig=w+'x'+h;if(sizeSig!==lastRouteSize){routeLayer.setAttribute('viewBox',`0 0 ${w} ${h}`);routeLayer.setAttribute('width',String(w));routeLayer.setAttribute('height',String(h));lastRouteSize=sizeSig;lastRoutePoints=''}const screen=pts.map(p=>mapToScreen(p.map_x,p.map_y));const points=screen.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ');const last=screen[screen.length-1];const sig=(navMode?'1':'0')+'|'+points+'|'+last.x.toFixed(1)+','+last.y.toFixed(1);if(sig!==lastRoutePoints){lastRoutePoints=sig;const els=ensureRouteEls();els.outer.setAttribute('points',points);els.inner.setAttribute('points',points);els.dest.setAttribute('cx',last.x.toFixed(1));els.dest.setAttribute('cy',last.y.toFixed(1))}routeLayer.style.display=navMode?'block':'none';applyMapRotation()}
function maybeFinishNavigation(){if(!navMode||!routeTarget||!telemetry||telemetry.map_x===null)return false;const now=Date.now();const px=Number(telemetry.map_x),py=Number(telemetry.map_y);const speed=Number(telemetry.speed_kmh)||0;const directPx=dist({map_x:px,map_y:py},routeTarget);const routePts=routePointsForRender();const routePx=routePts.length>=2?routeDistancePx(routePts):Infinity;const arrivePx=Math.min(directPx,routePx);const limitPx=(speed<=NAV_ARRIVE_STOPPED_MAX_KMH)?NAV_ARRIVE_STOPPED_PX:NAV_ARRIVE_PX;if(arrivePx<=limitPx){if(!arriveSince)arriveSince=now;if(now-arriveSince>=NAV_ARRIVE_HOLD_MS){exitNavMode(true,true);return true}}else if(arrivePx>limitPx*1.35){arriveSince=0}return false}
function updateNavUi(){if(!navMode)return;const speed=Math.round((telemetry&&telemetry.speed_kmh)||0);document.getElementById('navSpeedBubble').textContent=speed+' km/h';const compass=document.getElementById('navCompass');if(telemetry){compass.textContent=northUp?'N · north up':`${Math.round(normalizeAngleDeg(displayHeadingDeg||0))}° · heading up`}const target=routeTarget;document.getElementById('navTargetName').textContent=target?target.title:'No destination';if(!telemetry||telemetry.map_x===null||!target){document.getElementById('navDistance').textContent='—';document.getElementById('navEta').textContent='—';document.getElementById('navInstruction').textContent='Select a POI and press Build route';document.getElementById('navSub').textContent='Heading-up navigation preview';renderRouteLine();return}const routePts=routePointsForRender();const remainingPx=routePts.length>=2?routeDistancePx(routePts):dist({map_x:telemetry.map_x,map_y:telemetry.map_y},target);const meters=Math.max(0,Math.round(metersFromMapPx(remainingPx)));const km=meters>=1000?(meters/1000).toFixed(1)+' km':meters+' m';const etaMin=Math.max(1,Math.round((meters/1000)/Math.max(15,telemetry.speed_kmh||0)*60));document.getElementById('navDistance').textContent=km;document.getElementById('navEta').textContent=etaMin+' min';const mode=currentRoute&&currentRoute.mode?currentRoute.mode:'none';const failed=currentRoute&&currentRoute.ok===false;let titlePrefix=routeRequestInFlight?'Recalculating: ':(failed?'No road route to ':(mode==='graph'?'Route to ':(mode==='direct'?'Direct to ':'Route to ')));let routeKind=failed?(currentRoute.message||'road graph failed'):(mode==='graph'?'road graph route':(mode==='direct'?'direct preview: no graph loaded':'waiting for route'));document.getElementById('navInstruction').textContent=titlePrefix+target.title;const navRouteHint=routeRequestInFlight?' · recalculating…':((offRouteSince&&lastRouteOffRoutePx>REROUTE_STICKY_OFF_PX&&!failed)?' · holding original route':(lastRouteOffRoutePx>42&&!failed?' · return to route':''));const arrivalHint=arriveSince?' · arriving…':'';document.getElementById('navSub').textContent=`${km} · ${target.category||'POI'} · ${routeKind}${navRouteHint}${arrivalHint}`;document.getElementById('navArrow').textContent=failed?'!':'↑';renderRouteLine()}
async function sendMediaKey(action){const el=document.getElementById('musicStatus');try{const r=await fetch('/api/media/'+action,{method:'POST'});const data=await r.json();el.textContent=data.ok?'Sent: '+action:(data.error||'Media key failed')}catch(e){el.textContent='Media key failed'}setTimeout(()=>{if(el)el.textContent='Windows media keys'},1600)}
function isMobileOrTablet(){return /Android|iPhone|iPad|iPod|Mobile|Tablet/i.test(navigator.userAgent)||((navigator.maxTouchPoints||0)>1&&Math.min(window.innerWidth,window.innerHeight)<1024)}
async function loadServerInfo(){const panel=document.getElementById('pcLinkPanel');if(panel&&isMobileOrTablet()){panel.classList.add('hideOnDevice');return}try{const r=await fetch('/api/info',{cache:'no-store'});const info=await r.json();const el=document.getElementById('phoneUrl');const btn=document.getElementById('copyIpBtn');const qr=document.getElementById('phoneQr');const url=(info.phone_urls&&info.phone_urls.length)?info.phone_urls[0]:location.origin;if(el)el.textContent=url;if(qr)qr.src='/api/qr.svg?text='+encodeURIComponent(url);if(btn)btn.onclick=async()=>{try{await navigator.clipboard.writeText(url);btn.textContent='Copied';setTimeout(()=>btn.textContent='Copy',1200)}catch(e){btn.textContent='Copy failed';setTimeout(()=>btn.textContent='Copy',1200)}}}catch(e){const el=document.getElementById('phoneUrl');if(el)el.textContent=location.origin}}
function nearestDistanceTextFromPx(dpx){const meters=Math.max(0,Math.round(metersFromMapPx(dpx)));return meters>=1000?(meters/1000).toFixed(1)+' km':meters+' m'}
function updateNearest(){const lists=[...document.querySelectorAll('[data-nearest-list]')];if(!lists.length)return;function setAll(html){for(const list of lists)list.innerHTML=html}if(!telemetry||telemetry.map_x===null){setAll('<div class="hint">Waiting for telemetry…</div>');return}if(!markers||!markers.length){setAll('<div class="hint">POI markers are loading…</div>');return}const p={map_x:telemetry.map_x,map_y:telemetry.map_y};let pool=markers;if(categoryFilter)pool=pool.filter(m=>m.category===categoryFilter);const near=pool.map(m=>({...m,dist:dist(p,m)})).sort((a,b)=>a.dist-b.dist).slice(0,4);for(const list of lists){list.innerHTML="";for(const n of near){const div=document.createElement('div');div.className='nearItem clickable';const selected=selectedPoi&&String(selectedPoi.markerId||selectedPoi.id)===String(n.markerId||n.id);div.innerHTML=`<span><b>${selected?'▶ ':''}${esc(n.title)}</b><br><span class="sub">${esc(n.category)}</span></span><span>${nearestDistanceTextFromPx(n.dist)}</span>`;div.onpointerdown=(ev)=>{ev.stopPropagation();selectPoi(n,false)};list.appendChild(div)}}}
function initSearch(){const input=document.getElementById('searchInput'),clear=document.getElementById('searchClearBtn');if(!input)return;input.addEventListener('input',()=>runSearch(input.value));input.addEventListener('focus',()=>runSearch(input.value));input.addEventListener('keydown',ev=>{if(ev.key==='Enter'){const first=document.querySelector('.searchItem');if(first)first.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}))}});if(clear)clear.onclick=()=>{input.value='';runSearch('');input.focus()}}
function markerDistanceText(m){if(!telemetry||telemetry.map_x===null)return'';const dpx=dist({map_x:telemetry.map_x,map_y:telemetry.map_y},m);const meters=Math.round(metersFromMapPx(dpx));return meters>=1000?(meters/1000).toFixed(1)+' km':meters+' m'}
function runSearch(raw){const box=document.getElementById('searchResults');if(!box)return;const q=String(raw||'').trim().toLowerCase();if(q.length<2){box.classList.remove('open');box.innerHTML='';return}let pool=markers||[];if(categoryFilter)pool=pool.filter(m=>m.category===categoryFilter);const terms=q.split(/\s+/).filter(Boolean);let results=pool.filter(m=>{const hay=[m.title,m.category,m.parent_category,m.description].filter(Boolean).join(' ').toLowerCase();return terms.every(t=>hay.includes(t))});if(telemetry&&telemetry.map_x!==null){const p={map_x:telemetry.map_x,map_y:telemetry.map_y};results=results.map(m=>({...m,_d:dist(p,m)})).sort((a,b)=>(a._d||0)-(b._d||0))}else{results=results.sort((a,b)=>String(a.title).localeCompare(String(b.title)))}results=results.slice(0,8);box.classList.add('open');if(!results.length){box.innerHTML='<div class="searchEmpty">Nothing found. Try another POI name/category.</div>';return}box.innerHTML='';for(const m of results){const div=document.createElement('div');div.className='searchItem';div.innerHTML=`<div><div class="searchItemTitle">${esc(m.title)}</div><div class="searchItemMeta">${esc(m.category||'POI')}${m.parent_category?' · '+esc(m.parent_category):''}${markerDistanceText(m)?' · '+markerDistanceText(m):''}</div></div><button title="Build route">Route</button>`;div.onpointerdown=(ev)=>{if(ev.target&&ev.target.tagName==='BUTTON')return;ev.stopPropagation();selectPoi(m,false)};div.querySelector('button').onpointerdown=(ev)=>{ev.preventDefault();ev.stopPropagation();startRouteToPoi(m)};box.appendChild(div)}}
function esc(s){return String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function updateHud(){if(!telemetry)return;const hasError=!!telemetry.udp_error;const on=!hasError&&!!telemetry.receiving;const hasPos=telemetry.map_x!==null&&telemetry.map_y!==null;const dot=document.getElementById('statusDot');dot.classList.toggle('on',on);document.getElementById('statusText').textContent=hasError?'UDP ERROR':(telemetry.pause_coordinate_hold?'HOLDING':(on?'LIVE':(hasPos?'HOLDING':'WAITING')));document.getElementById('speed').textContent=Math.round(telemetry.speed_kmh||0);document.getElementById('gear').textContent=telemetry.gear||'-';document.getElementById('heading').textContent=Math.round(telemetry.heading_deg||0);document.getElementById('mapxy').textContent=telemetry.map_x!==null?`${Math.round(telemetry.map_x)}, ${Math.round(telemetry.map_y)}`:'—'}
function renderAll(force=false){renderTiles(force);renderPlayer();renderMarkers();renderMapPickMarker();updateNearest();renderRouteLine();updateNavUi()}
function renderInteractionFrame(){interactionRenderRaf=0;renderTiles();renderPlayer();renderRouteLine();renderMarkers();renderMapPickMarker();updateNavUi()}
function scheduleInteractionRender(){if(interactionRenderRaf)return;interactionRenderRaf=requestAnimationFrame(renderInteractionFrame)}
function lerpAngleDeg(current,target,alpha){let delta=((target-current+540)%360)-180;return current+delta*alpha}
function animationLoop(){try{if(targetMapX!==null&&targetMapY!==null){if(displayMapX===null){displayMapX=targetMapX;displayMapY=targetMapY;displayHeadingDeg=targetHeadingDeg}else{const posAlpha=navMode?0.16:0.24;displayMapX+=(targetMapX-displayMapX)*posAlpha;displayMapY+=(targetMapY-displayMapY)*posAlpha;displayHeadingDeg=lerpAngleDeg(displayHeadingDeg,targetHeadingDeg,0.14)}playerMapX=displayMapX;playerMapY=displayMapY;maybeAutoZoomNavigation();centerIfFollowing();renderTiles();renderPlayer();renderRouteLine();renderMapPickMarker();if(!maybeFinishNavigation()){updateNavUi();maybeRerouteNavigation()}applyMapRotation();const now=performance.now();if(now-lastMarkerRenderAt>260){renderMarkers();lastMarkerRenderAt=now}if(now-lastNearestRenderAt>700){updateNearest();lastNearestRenderAt=now}}}catch(e){console.warn('animation error',e)}requestAnimationFrame(animationLoop)}
async function pollTelemetry(){try{const r=await fetch('/api/state?ts='+Date.now(),{cache:'no-store'});telemetry=await r.json();updateHud();if(telemetry&&telemetry.map_x!==null){targetMapX=Number(telemetry.map_x);targetMapY=Number(telemetry.map_y);targetHeadingDeg=updateHeadingFromMotion(targetMapX,targetMapY,Number(telemetry.speed_kmh)||0,telemetry.heading_deg||0);if(displayMapX===null){displayMapX=targetMapX;displayMapY=targetMapY;displayHeadingDeg=targetHeadingDeg;playerMapX=displayMapX;playerMapY=displayMapY;}}}catch(e){console.warn('telemetry poll error',e)}finally{setTimeout(pollTelemetry,120)}}
async function loadMarkers(){try{const r=await fetch('/api/markers?ts='+Date.now(),{cache:'no-store'});const data=await r.json();markers=Array.isArray(data)?data:[];console.log('POI markers loaded',markers.length)}catch(e){console.warn('markers fetch error',e);markers=[]}try{populateCategories();renderTiles(true);renderMarkers();updateNearest()}catch(renderError){console.warn('markers render error',renderError)}}
function pointerDistance(){const pts=[...activePointers.values()];if(pts.length<2)return 0;const dx=pts[0].x-pts[1].x,dy=pts[0].y-pts[1].y;return Math.sqrt(dx*dx+dy*dy)}
function pointerCenter(){const pts=[...activePointers.values()];return{x:(pts[0].x+pts[1].x)/2,y:(pts[0].y+pts[1].y)/2}}
viewport.addEventListener('pointerdown',e=>{
  if(e.button===2)return;
  if(e.target.closest&&e.target.closest('.marker,.poiPopup,.mapContextMenu,.nearest,.searchPanel,.musicWidget,.navBottomBar,.navTopInstruction,.cachePanel,.mobileDock,.mobileSheet,.mobileSheetClose,.mobileNearestOverlay,.navInfoToggle,.navMediaToggle'))return;
  activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  tapStart={id:e.pointerId,x:e.clientX,y:e.clientY,t:Date.now()};tapWasMulti=false;
  if(e.target===viewport||e.target.id==='mapWorld'||e.target.id==='tileLayer'||e.target.id==='playerLayer')clearPoi();
  try{viewport.setPointerCapture(e.pointerId)}catch(_){}
  if(activePointers.size===2){
    tapWasMulti=true;tapStart=null;pinchStart={dist:pointerDistance(),zoom};lastPinchZoom=zoom;dragging=false;dragStart=null;viewport.classList.remove('dragging');
    if(navMode)keepNavigatorFollow();
    return;
  }
  dragging=true;
  if(navMode&&follow){keepNavigatorFollow();centerOnPlayer()}
  else{follow=false;document.getElementById('followBtn').classList.remove('active')}
  viewport.classList.add('dragging');
  dragStart={x:e.clientX,y:e.clientY,panX,panY};
});
viewport.addEventListener('pointermove',e=>{
  if(!activePointers.has(e.pointerId))return;
  activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(tapStart&&tapStart.id===e.pointerId&&Math.hypot(e.clientX-tapStart.x,e.clientY-tapStart.y)>22)tapStart=null;
  if(activePointers.size>=2&&pinchStart){
    if(navMode)keepNavigatorFollow();
    const d=pointerDistance();
    if(d>0&&pinchStart.dist>0){
      const ratio=d/pinchStart.dist;let target=pinchStart.zoom;
      if(ratio>1.18)target=pinchStart.zoom+1;if(ratio>1.55)target=pinchStart.zoom+2;if(ratio<0.85)target=pinchStart.zoom-1;if(ratio<0.62)target=pinchStart.zoom-2;
      target=clamp(target,MIN_ZOOM,MAX_ZOOM);
      if(target!==lastPinchZoom){const c=pointerCenter();setZoom(target,c.x,c.y);lastPinchZoom=target}
    }
    return;
  }
  if(navMode&&follow){keepNavigatorFollow();centerOnPlayer();return}
  if(!dragging||!dragStart)return;
  panX=dragStart.panX-(e.clientX-dragStart.x);panY=dragStart.panY-(e.clientY-dragStart.y);clampPan();scheduleInteractionRender();
});
function endPointer(e){const wasTap=!!(tapStart&&tapStart.id===e.pointerId&&!tapWasMulti&&Math.hypot(e.clientX-tapStart.x,e.clientY-tapStart.y)<=22&&(Date.now()-tapStart.t)<650);activePointers.delete(e.pointerId);if(activePointers.size<2)pinchStart=null;if(activePointers.size===0){dragging=false;dragStart=null;tapWasMulti=false;viewport.classList.remove('dragging');if(wasTap)maybeHandleDoubleTap(e);tapStart=null;if(navMode&&follow){keepNavigatorFollow();centerOnPlayer();renderTiles(true);renderPlayer();renderRouteLine();renderMapPickMarker();updateNavUi()}}}
viewport.addEventListener('pointerup',endPointer);viewport.addEventListener('pointercancel',endPointer);
viewport.addEventListener('contextmenu',e=>{e.preventDefault();if(e.target.closest&&e.target.closest('.marker,.poiPopup,.mapContextMenu,.nearest,.searchPanel,.musicWidget,.navBottomBar,.navTopInstruction,.cachePanel,.mobileDock,.mobileSheet,.mobileSheetClose,.mobileNearestOverlay,.navInfoToggle,.navMediaToggle'))return;showContextMenuForScreen(e.clientX,e.clientY,false)},{passive:false});
viewport.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?1:-1),e.clientX,e.clientY)},{passive:false});
window.addEventListener('resize',()=>{setMobileUiClass();if(!isMobileLayout())closeMobilePanels();centerIfFollowing();renderAll(true)});
setMobileUiClass();initControls();loadServerInfo();centerOnPlayer();renderTiles(true);requestAnimationFrame(animationLoop);pollTelemetry();loadMarkers();
